# -*- coding: utf-8 -*-
"""Final_Year_Project the end.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17HAeO_x2v_sM6mUGnHWYLKgBitOAf7bc
"""

import numpy as np
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
from datetime import datetime

!pip install -q -U keras-tuner
import kerastuner as kt

data=pd.read_csv('/content/sample_data/continuous_dataset.csv')
data.head()

hourOfDay=[]
weekDay=[]
weekend=[]
for i in range(48048):
    hourOfDay.append(int(data['datetime'][i][11:13]))
    weekDay.append(datetime.weekday(datetime.strptime(data['datetime'][i], '%Y-%m-%d %H:%M:%S')))
    if(weekDay[i]>4):
        weekend.append(1)
    else:
        weekend.append(0)
data['hourOfDay']=hourOfDay
data['weekDay']=weekDay
data['weekend']=weekend
output=data['nat_demand']
data=data.drop('nat_demand',axis=1)


data=data.drop('datetime',axis=1)
data

normalized_df=(data-data.mean())/data.std()

data=normalized_df

def inputData(data,start,end):
    batch=np.empty([end-start,168,19,3])
    for i in range (start,end):
        xin=np.stack((np.insert(np.array(data.iloc[i:i+168]),18,output[:168],axis=1),np.insert(np.array(data.iloc[i+168:i+168+168]),18,output[i+168+168:i+168+168+168],axis=1),np.insert(np.array(data.iloc[:168]),18,output[:168],axis=1)),axis=2)
        batch[i-start]=xin
    return np.array(batch)

trianOutput=np.array(output[504:36540])
trainInput=inputData(data,0,36036)
testOutput=np.array(output[36540:48048])
testInput=inputData(data,36036,47544)

device_name = tf.test.gpu_device_name()
if len(device_name) > 0:
    print("Found GPU at: {}".format(device_name))
else:
    device_name = "/device:CPU:0"
    print("No GPU, using {}.".format(device_name))

with tf.device(device_name):
  model = models.Sequential()
  kernelHeight=5
  kernelWidth=2
  featureMap=15
  stride=1
  model.add(layers.Conv2D(featureMap, (kernelHeight, kernelWidth), strides=(stride,1), activation='relu', input_shape=(168, 19,3)))

  maxPoolWidth=3
  stride=1
  model.add(layers.MaxPooling2D((maxPoolWidth, 1),strides=(stride,1)))

  kernelHeight=5
  kernelWidth=2
  featureMap=15
  stride=1
  model.add(layers.Conv2D(featureMap, (kernelHeight, kernelWidth), strides=(stride,1), activation='relu'))

  maxPoolWidth=2
  stride=1
  model.add(layers.MaxPooling2D((maxPoolWidth, 1),strides=(stride,1)))

  kernelHeight=5
  kernelWidth=2
  featureMap=30
  stride=1
  model.add(layers.Conv2D(featureMap, (kernelHeight, kernelWidth), strides=(stride,1), activation='relu', input_shape=(168, 19,3)))

  maxPoolWidth=2
  stride=1
  model.add(layers.MaxPooling2D((maxPoolWidth, 1),strides=(stride,1)))

  kernelHeight=5
  kernelWidth=2
  featureMap=60
  stride=1
  model.add(layers.Conv2D(featureMap, (kernelHeight, kernelWidth), strides=(stride,1), activation='relu', input_shape=(168, 19,3)))

  maxPoolWidth=2
  stride=1
  model.add(layers.MaxPooling2D((maxPoolWidth, 1),strides=(stride,1)))

  kernelHeight=5
  kernelWidth=2
  featureMap=60
  stride=1
  model.add(layers.Conv2D(featureMap, (kernelHeight, kernelWidth), strides=(stride,1), activation='relu', input_shape=(168, 19,3)))

  maxPoolWidth=2
  stride=1
  model.add(layers.MaxPooling2D((maxPoolWidth, 1),strides=(stride,1)))

  kernelHeight=5
  kernelWidth=2
  featureMap=60
  stride=1
  model.add(layers.Conv2D(featureMap, (kernelHeight, kernelWidth), strides=(stride,1), activation='relu', input_shape=(168, 19,3)))

  maxPoolWidth=2
  stride=1
  model.add(layers.MaxPooling2D((maxPoolWidth, 2),strides=(stride,1)))

  kernelHeight=5
  kernelWidth=2
  featureMap=60
  stride=1
  model.add(layers.Conv2D(featureMap, (kernelHeight, kernelWidth), strides=(stride,1), activation='relu', input_shape=(168, 19,3)))

  maxPoolWidth=2
  stride=1
  model.add(layers.MaxPooling2D((maxPoolWidth, 1),strides=(stride,1)))

  kernelHeight=5
  kernelWidth=2
  featureMap=60
  stride=1
  model.add(layers.Conv2D(featureMap, (kernelHeight, kernelWidth), strides=(stride,1), activation='relu', input_shape=(168, 19,3)))

  maxPoolWidth=2
  stride=1
  model.add(layers.MaxPooling2D((maxPoolWidth, 1),strides=(stride,1)))

  kernelHeight=5
  kernelWidth=3
  featureMap=60
  stride=1
  model.add(layers.Conv2D(featureMap, (kernelHeight, kernelWidth), strides=(stride,1), activation='relu', input_shape=(168, 19,3)))

  maxPoolWidth=2
  stride=1
  model.add(layers.MaxPooling2D((maxPoolWidth, 2),strides=(stride,1)))

  kernelHeight=5
  kernelWidth=3
  featureMap=60
  stride=1
  model.add(layers.Conv2D(featureMap, (kernelHeight, kernelWidth), strides=(stride,1), activation='relu', input_shape=(168, 19,3)))

  maxPoolWidth=2
  stride=1
  model.add(layers.MaxPooling2D((maxPoolWidth, 2),strides=(stride,1)))

  kernelHeight=5
  kernelWidth=3
  featureMap=60
  stride=1
  model.add(layers.Conv2D(featureMap, (kernelHeight, kernelWidth), strides=(stride,1), activation='relu', input_shape=(168, 19,3)))

  maxPoolWidth=2
  stride=1
  model.add(layers.MaxPooling2D((maxPoolWidth, 2),strides=(stride,1)))

  model.add(layers.Flatten())
  model.add(layers.Dense(128, activation='relu'))
  model.add(layers.Dropout(0.3))
  model.add(layers.Dense(1))
  model.compile(optimizer="adam", loss="mae", metrics=["mse"])
  model.summary()
  hist=model.fit(trainInput,trianOutput,epochs=20,validation_data=(testInput,testOutput))

plt.plot(hist.history['val_loss'])
plt.title('model loss')
plt.ylabel('val loss')
plt.xlabel('epoch')

import gc
del(trainInput)
del(testInput)
gc.collect()

del(trianOutput)
del(testOutput)
del(hourOfDay)
del(weekDay)
del(weekend)
gc.collect()

validInput=inputData(data,0,47544)

del(data)
gc.collect()

validOutput=np.array(output[504:48048])

y_pred=model.predict(validInput)

del(validInput)
gc.collect()

gc.collect()

x=np.arange(1,101)
predicted=plt.plot(x,y_pred[100:200],color='r', label='predicted')
actual=plt.plot(x,validOutput[100:200],color='g', label='actual')

plt.xlabel('hours')
plt.ylabel('load')
leg = plt.legend(loc='upper right')
plt.show()

x=np.arange(1,61)
plt.plot(x,y_pred[36540:36600],color='r', label='predicted')
plt.plot(x,validOutput[36540:36600],color='g', label='actual')
plt.xlabel('hours')
plt.ylabel('load')
leg = plt.legend(loc='upper right')
plt.show()

sum = 0
for i in range(36540,47544):
    sum += abs(validOutput[i] - y_pred[i])/validOutput[i]

error = sum/(47544-36540)

# display
print("Mean absolute error : " + str(error*100))

model.save("my_model")

model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model.h5")

